name: Run tests

on:
  push:
    branches:
      - master
      - main
  pull_request:
    types: [opened, synchronize, reopened]

# needed to allow julia-actions/cache to delete old caches that it has created
permissions:
  actions: write
  contents: read

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version: ['lts', '1', 'pre']
        os: [ubuntu-latest, windows-latest, macOS-latest]
        arch:
          - x64
        include:
          # Add aarch64 (Apple Silicon) for macOS
          - os: macOS-latest
            version: 'lts'
            arch: aarch64
          - os: macOS-latest
            version: '1'
            arch: aarch64
          - os: macOS-latest
            version: 'pre'
            arch: aarch64
        exclude:
          # Use aarch64 for macOS-latest (Apple Silicon) instead of x64
          - os: macOS-latest
            arch: x64

    steps:
      - uses: actions/checkout@v7
      - uses: julia-actions/setup-julia@v3
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v3
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v7
        with:
          files: lcov.info
